spring:
  datasource:
    url: jdbc:postgresql://ep-autumn-violet-ah2a9n82-pooler.c-3.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
    username: neondb_owner
    password: npg_DlJ16SXCjiBk
    driver-class-name: org.postgresql.Driver



  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always

server:
  port: ${PORT}